### ISSUE TITLE
It will cause crash on Android release version

### ISSUE THREAD

**Issue by raymanyoung** [remobile/react-native-splashscreen#11]
It works fine on debug version with emulator/device, but the release version will crash on device with following log

```
Activity com.diary.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42bda540 V.E..... R.....ID 0,0-720,1280} that was originally added here
                                                  android.view.WindowLeaked: Activity com.diary.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42bda540 V.E..... R.....ID 0,0-720,1280} that was originally added here
                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:454)
                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:258)
                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:73)
                                                      at android.app.Dialog.show(Dialog.java:287)
                                                      at com.remobile.splashscreen.RCTSplashScreen$3.run(RCTSplashScreen.java:129)
                                                      at android.os.Handler.handleCallback(Handler.java:730)
                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                      at android.os.Looper.loop(Looper.java:137)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                      at dalvik.system.NativeStart.main(Native Method)
```

Environment: Windows + Android. RN 0.17

**Comment by M1chaelTran** [comment]
I'm getting the same error

**Comment by mtebele** [comment]
Any fix?

**Comment by edencakir** [comment]
+

**Comment by duongntb94** [comment]
I'm getting the same error.

**Comment by rodrigoxavier** [comment]
No one know how to solve it?
